<?php
declare(strict_types = 1);

namespace DataTables\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController {

	/**
	 * @return void
	 */
	public function initialize(): void {
		parent::initialize(); // TODO: Change the autogenerated stub

	}

}
